### ISSUE TITLE
Will you share the training code of the Atari?

### ISSUE THREAD

**Issue by GoingMyWay** [galdl/rl_delay_basic#1]
Hi, will you share the training code of the Atari?

By the way, can you specify the version of the dependencies? For example the version of Tensorflow, Keras and wandb.

**Comment by galdl** [comment]
Hi, yes the Atari code is undergoing Nvidia's code release process for licensing purposes and will be released when it's done.

RE dependencies -- that's a good point. I'll specify them in the readme.

**Comment by GoingMyWay** [comment]
Thank you, that would be great.

**Comment by galdl** [comment]
Regarding the dependency versions, I updated requirements.txt with all needed packages and versions. Tell me if it works now :)

**Comment by GoingMyWay** [comment]
Hi, I tried the new requirement.txt, and it shows 

```
AttributeError: module 'tensorflow.python.keras.utils.generic_utils' has no attribute 'populate_dict_with_module_objects'
```

I also tried TF with 1.14, and it works fine.

**Comment by GoingMyWay** [comment]
Please also add this code in order to reduce unnecessary GPU memory overhead.

```
from keras import backend as K
import tensorflow as tf

config = tf.ConfigProto(allow_soft_placement=True)
config.gpu_options.per_process_gpu_memory_fraction = 0.9
config.gpu_options.allow_growth = True
sess = tf.Session(config=config)
K.set_session(sess)
```

**Comment by GoingMyWay** [comment]
Hi, BTW, can you also provide the best parameters of each algorithm and each environment to reproduce the results in the paper?

**Comment by galdl** [comment]
Thank you for the code you added. Now, instead of me adding it manually, how about we do this the proper way and make you a contributor? Do you want to add it through a PR?

And thank you for raising the point regarding the parameters in the paper. The default ones appearing in init_main.py are the ones I used for all agents and all environments (i.e. cartpole and acrobot for this repo) in the paper. The only difference is for a single parameter: for cartpole I used epsilon_decay=0.999, while for acrobot it is epsilon_decay=0.9999. I believe this is one of the strengths of this algorithm -- almost no parameter tuning were needed to get it working well.

The two parameters above are given in a comment in the code, but I'll also add a short explanation to the readme. 

Lastly, I added an example wandb sweep file.

**Comment by GoingMyWay** [comment]
> Thank you for the code you added. Now, instead of me adding it manually, how about we do this the proper way and make you a contributor? Do you want to add it through a PR?
> 
> And thank you for raising the point regarding the parameters in the paper. The default ones appearing in init_main.py are the ones I used for all agents and all environments (i.e. cartpole and acrobot for this repo) in the paper. The only difference is for a single parameter: for cartpole I used epsilon_decay=0.999, while for acrobot it is epsilon_decay=0.9999. I believe this is one of the strengths of this algorithm -- almost no parameter tuning were needed to get it working well.
> 
> The two parameters above are given in a comment in the code, but I'll also add a short explanation to the readme.
> 
> Lastly, I added an example wandb sweep file.

Hi, @galdl I will make a PR soon.
